services:
  db:
    images: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - 54327:5432
    environments:
      - POSTGRES_PASSWORD=sirinya@94
      - POSTGRES_USER=sirinya
      - POSTGRES_DB=sirinya
    volumes:
      - ./data/data:/var/lib/postgresql/data
